### ISSUE TITLE
MAUI -- Me Too Movement???

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [triaxis-oss/triaxis.Xamarin.BluetoothLE#4] opened 2022-06-12 04:50 UTC
Just chiming in to voice my support for Maui....   Where can documentation be found?

**Comment by SolidStateLEDLighting** [comment] 2022-06-12 05:20
I'm reluctant to spend any time on this if the likelihood of success is small.   Does the software work inside Maui?

**Comment by ssimek** [comment] 2022-06-12 15:18
Closing as duplicate of #3

**Closed as completed by ssimek** 2022-06-12 15:18 UTC
